### ISSUE TITLE
hi, i have 2 problems for it?

### ISSUE THREAD

**Issue by sgf** [gammasoft71/xtd_properties#2]
1.does this way will make the build output file more large(because use template)?
2.have overhead(because with a wapper by a template class)?

for me overhead is not important.
But I care a lot about binary size.

In fact, I'm compiling your Switch project(your Old Porject) as a static library(.lib), in Debug mode, I get 600mb output, and in Release mode, I get 1GB output
**I'm not sure if this(The Properties) is causing very large results.**
**in Release Mode(when im close the Whole Program Optimization),im also got 300mb Switch.lib file size.**

Switch version(2018-06-18 14:54:51) this is what i can find  the last version 

I am a C ++ noob. Before that I was a C # programmer. Forgive me for not being able to write a C # -like BCL library by myself.

**Comment by sgf** [comment]
Sorry, maybe I asked too many questions. In order to avoid disturbing you, I closed it.

**Comment by gammasoft71** [comment]
In C++ each implementation of a template class for a specific type will take up a certain amount of memory. 
This doesn't necessarily mean that the final optimized binary (memory/speed oriented e.g. -o3) will be larger if you use the class property rather than if you had written specific accessors for each member.

Note: No support for Switch project. Switch is a private project which has been made public by mistake. Switch has been removed.
