### ISSUE TITLE
a problem,maybe not a problem

### ISSUE THREAD

**Issue by sgf** [gammasoft71/xtd_properties#3]
//Exception.h
```C++
struct String; //avoid include loop
struct Exception{
property_<const String&, readonly_> Message{ get_ {return this->GetMessage(); } 
const String& GetMessage() const;
}
```

give me error undefine identity String

but normal code(a function) is build pass;

`const String& Message() {return this->GetMessage(); } `

**Comment by gammasoft71** [comment]
Yes of course, it same as a method, you can't return an object undefined.
You must define your property like a method, declaration in header and implementation in source file. For properties the implementation must be in the constructor because is a member of your class.

See example below :

Person.h:

// forward declaration of String
class String;

class Person {
public:
  Person();

  property_<const String&, readonly_> Name;  
 // ...
};

Person.cpp:
#include <String.h>

const String& GetName() {
  // ...
}

Person::Person() : Name(get_ {return GetName();}) {
}

**Comment by sgf** [comment]
thanks very much

**Comment by sgf** [comment]
or this:
`p_<const String&, readonly_> Message{ get_-> const String& {return this->GetMessage(); } };`
