### ISSUE TITLE
Static properties

### ISSUE THREAD

**Issue by bstordrup** [gammasoft71/xtd_properties#4]
Hi

Does the library support defining static properties on a class - including static classes?

**Comment by gammasoft71** [comment]
Hi,

First of all thank you for your interest in properties 😉

You can create static property  like this :

```c++
class my_class {
public:
  //...
  my_class() = delete;

  inline static property_<std::string> name {
    get_ {return name_;},
    set_ {name_ = value;},
  };

  //...

private:
  inline static std::string name_;
};
```

**Comment by bstordrup** [comment]
Can the property getter and setter be implemented in `my_class.cpp` (assuming `my_class` is defined in `my_class.h`)

**Comment by gammasoft71** [comment]
You can also do it like this :

my_class.h :
```c++
class my_class {
public:
  //...
  my_class() = delete;

  static property_<std::string> name;

  //...

private:
  static std::string name_;
};
```

my_class.cpp :

```c++
#include "my_class.h"

std::string my_class::name_;

property_<std::string> my_class::name {
  get_ {return name_;},
  set_ {name_ = value;},
};
```

**Comment by bstordrup** [comment]
Nice. Using the library - it's enough to include the `xtd.properties.h` file`?

**Comment by gammasoft71** [comment]
Yes…

**Comment by bstordrup** [comment]
Thank you

**Comment by gammasoft71** [comment]
you're welcome.

**Comment by bstordrup** [comment]
Non-static properties - can they be implemented in .cpp file also?

**Comment by gammasoft71** [comment]
Yes and no...
Property works exactly like any other native type or class. In fact, the property is a template class containing two std::functions (one for the setter and one for the getter).
You can therefore initialize it in the header file like any other type. Or in the constructor of the parent class. If you implement the constructor in the cpp file, the implementation of the property will be in the cpp file.

For example : 

my_class.h :
```c++
class my_class {
public:
  //...
  my_class();

  property_<std::string> name;
  property_<int> age;

  //...

private:
  std::string name_;
  int age_;
};
```

my_class.cpp :
```c++
#include "my_class.h"

my_class::my_class : 
  name(get_ {return name_;}, set_ {name_ = value}), 
  age(get_ {return age_;}, set_ {age_ = value;}),
  age_(0) {
}
```

Personally, since modern C++ 11, I prefer to initialize variables in the header, which is much easier to read unless the initialization value is not accessible. 😉
